import = ["/Users/m/.config/alacritty/colors.toml", "/Users/m/.config/alacritty/fonts.toml", "/Users/m/.config/alacritty/keybindings.toml"]
live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Select"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = false

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
faux_multiplier = 100
history = 100000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0
