[general]
import = ["/Users/ld/.config/alacritty/colors.toml", "/Users/ld/.config/alacritty/fonts.toml", "/Users/ld/.config/alacritty/keybindings.toml"]

live_config_reload = true

[bell]
duration = 0

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
action = "Select"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 0
lines = 0
