[colors]
transparent_background_colors = true

[[colors.indexed_colors]]
index = 16
color = "0x3ddbd9"

[[colors.indexed_colors]]
index = 17
color = "0xff7eb6"

[colors.primary]
background = "0x202020"
foreground = "0xf2f4f8"

[colors.normal]
black='0x282828'
red='0xee5396'
green='0x25be6a'
yellow='0x08bdba'
blue='0x78a9ff'
magenta='0xbe95ff'
cyan='0x33b1ff'
white='0xdfdfe0'

[colors.bright]
black='0x484848'
red='0xf16da6'
green='0x46c880'
yellow='0x2dc7c4'
blue='0x8cb6ff'
magenta='0xc8a5ff'
cyan='0x52bdff'
white='0xe4e4e5'

[colors.dim]
black = "#090909"
red = "#a04c40"
green = "#459a6f"
yellow = "#8f8800"
blue = "#607fca"
magenta = "#6f296a"
cyan = "#5c8482"
white = "#aaaaaa"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#c5c8c6"
foreground = "#1d1f21"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
