[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
index = 16
color = '#d9b078'

[[colors.indexed_colors]]
index = 17
color = '#e085b2'

[colors.primary]
background = '#1a1a1a'
foreground = '#e0dedf'

dim_foreground = '#c0bcbf'
bright_foreground = '#d9d6da'

[colors.normal]
black='#2a2a2a'
red='#f04a9d'
green='#4fa281'
yellow='#d9ba6f'
blue='#6fa3fd'
magenta='#c48fff'
cyan='#5fa9b4'
white='#e1dbdf'

[colors.bright]
black='#4b4b4b'
red='#f469b0'
green='#6cc3a5'
yellow='#eece87'
blue='#7db3fd'
magenta='#d096fd'
cyan='#54c1d8'
white='#e4e2e5'

[colors.dim]
black = '#0b0b0b'
red = '#a9473e'
green = '#43896b'
yellow = '#c0aa69'
blue = '#5884d2'
magenta = '#7b3078'
cyan = '#4c8f96'
white = '#b0a8aa'

[colors.cursor]
cursor = 'CellForeground'
text = 'CellBackground'

[colors.footer_bar]
background = '#c5c8c6'
foreground = '#3a3a40'

[colors.hints.end]
background = '#1d1f21'
foreground = '#e9ff5e'

[colors.hints.start]
background = '#e9ff5e'
foreground = '#1d1f21'

[colors.line_indicator]
background = 'None'
foreground = 'None'

[colors.search.focused_match]
background = '#1a1a1a'
foreground = '#e0dedf'

[colors.search.matches]
background = '#e1dbdf'
foreground = '#3a3a40'

[colors.selection]
background = 'CellForeground'
text = 'CellBackground'

[colors.vi_mode_cursor]
cursor = 'CellForeground'
text = 'CellBackground'
