[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
index = 16
color = '#c0783f'

[[colors.indexed_colors]]
index = 17
color = '#b85f7a'

[colors.primary]
background = '#070707'
foreground = '#d0d0d0'

dim_foreground = '#8a8a8a'
bright_foreground = '#e6e6e6'

[colors.normal]
black='#2a2a2a'
red='#c8525f'
green='#5aa76c'
yellow='#b89445'
blue='#5f8fd3'
magenta='#9b6ac8'
cyan='#00aeca'
white='#e1dbdf'

[colors.bright]
black='#4b4b4b'
red='#df6a76'
green='#6fd084'
yellow='#d7b85c'
blue='#7aa8ee'
magenta='#b486e6'
cyan='#19d8e8'
white='#e4e2e5'

[colors.dim]
black = '#090909'
red = '#7e3139'
green = '#356b43'
yellow = '#75612f'
blue = '#3b5f92'
magenta = '#61437a'
cyan = '#007a86'
white = '#858585'

[colors.cursor]
cursor = 'CellForeground'
text = 'CellBackground'

[colors.footer_bar]
background = '#181818'
foreground = '#d0d0d0'

[colors.hints.end]
background = '#070707'
foreground = '#d7b85c'

[colors.hints.start]
background = '#d7b85c'
foreground = '#070707'

[colors.line_indicator]
background = 'None'
foreground = 'None'

[colors.search.focused_match]
background = '#070707'
foreground = '#e6e6e6'

[colors.search.matches]
background = '#262626'
foreground = '#e3e3e3'

[colors.selection]
background = 'CellForeground'
text = 'CellBackground'

[colors.vi_mode_cursor]
cursor = 'CellForeground'
text = 'CellBackground'
